"""Port registry and .env generation for scripts/new-instance.sh.

Kept importable so CI can test allocation and secret generation without Docker.
"""
from __future__ import annotations

import os
import re
import secrets
import socket
from pathlib import Path

DEFAULT_START_PORT = 8000
NAME_RE = re.compile(r"^[a-z0-9]([a-z0-9-]{0,46}[a-z0-9])?$")


class ProvisionError(ValueError):
    pass


def validate_name(name: str) -> str:
    name = (name or "").strip().lower()
    if not NAME_RE.match(name):
        raise ProvisionError(
            "NAME must be lowercase alphanumeric plus internal hyphens "
            "(used as COMPOSE_PROJECT_NAME), e.g. acme or clinic-west"
        )
    return name


def _parse_registry(path: Path) -> dict[str, int]:
    mapping: dict[str, int] = {}
    if not path.is_file():
        return mapping
    for raw in path.read_text().splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        try:
            mapping[parts[0]] = int(parts[1])
        except ValueError:
            continue
    return mapping


def port_in_use(port: int, host: str = "127.0.0.1") -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            sock.bind((host, port))
        except OSError:
            return True
    return False


def allocate_port(
    registry_path: str | Path,
    name: str,
    start: int = DEFAULT_START_PORT,
    *,
    persist: bool = True,
    check_bind: bool = True,
) -> int:
    """Return the port for name, allocating the next free one if new."""
    name = validate_name(name)
    path = Path(registry_path)
    mapping = _parse_registry(path)
    if name in mapping:
        return mapping[name]
    used = set(mapping.values())
    port = start
    while port in used or (check_bind and port_in_use(port)):
        port += 1
        if port > 65535:
            raise ProvisionError("No free port left below 65535")
    if persist:
        path.parent.mkdir(parents=True, exist_ok=True)
        existing = path.read_text() if path.is_file() else ""
        if existing and not existing.endswith("\n"):
            existing += "\n"
        path.write_text(existing + f"{name}\t{port}\n")
    return port


def generate_secret() -> str:
    return secrets.token_hex(32)


def generate_password() -> str:
    # 24 url-safe chars, printed once by new-instance.sh
    return secrets.token_urlsafe(18)


def render_env(
    *,
    name: str,
    tz: str,
    email: str,
    port: int,
    trusted_proxies: str,
    base_url: str | None = None,
    secrets_map: dict[str, str] | None = None,
) -> str:
    name = validate_name(name)
    keys = secrets_map or {
        "SECRET_KEY": generate_secret(),
        "CRM_API_KEY": generate_secret(),
        "CRM_STAGES_API_KEY": generate_secret(),
        "CRM_MCP_API_KEY": generate_secret(),
    }
    project = f"crm-{name}"
    hint = base_url or f"https://{name}.example.com"
    data_dir = f"./instances/{name}/data"
    env_file = f"./instances/{name}/.env"
    return f"""# Generated by scripts/new-instance.sh — mode 0600. Do not commit.
# Instance: {name}

SECRET_KEY={keys["SECRET_KEY"]}
DATABASE_URL=sqlite:///./data/crm.db
TZ={tz}

COMPOSE_PROJECT_NAME={project}
CRM_PORT={port}
CRM_DATA_DIR={data_dir}
CRM_ENV_FILE={env_file}

# Replace the hostname with the public name you put in Caddy.
BASE_URL={hint}
SECURE_COOKIES=true

CRM_API_KEY={keys["CRM_API_KEY"]}
CRM_STAGES_API_KEY={keys["CRM_STAGES_API_KEY"]}
CRM_MCP_API_KEY={keys["CRM_MCP_API_KEY"]}

# Compose-network CIDR covers default Docker bridges. CIDR matching is
# landing in a sibling PR; new-instance.sh rewrites this to the resolved
# gateway IP after first start so today's IP-only matcher still works.
TRUSTED_PROXIES={trusted_proxies}

# First admin is created via scripts/create_admin.py (one-time password
# printed to the terminal). Do not put BOOTSTRAP_ADMIN_PASSWORD here.
BOOTSTRAP_ADMIN_EMAIL={email}
BOOTSTRAP_ADMIN_NAME=Admin
"""


def write_env_file(path: str | Path, contents: str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(str(path), os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    try:
        os.write(fd, contents.encode())
    finally:
        os.close(fd)
    os.chmod(path, 0o600)
    return path
